// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv37aOe7N0EcsTEepYSA96wXo2AfbytUk',
    appId: '1:173451887290:web:736bd1a81d240c0a8a3883',
    messagingSenderId: '173451887290',
    projectId: 'gooddeeds-app-4303c',
    authDomain: 'gooddeeds-app-4303c.firebaseapp.com',
    storageBucket: 'gooddeeds-app-4303c.firebasestorage.app',
    measurementId: 'G-3NE1V1HY79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVMKJj3tygrApJasfolaSZJUcBefjA0WU',
    appId: '1:173451887290:android:d532c317900f880c8a3883',
    messagingSenderId: '173451887290',
    projectId: 'gooddeeds-app-4303c',
    storageBucket: 'gooddeeds-app-4303c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv6z3xYtiiqLv4GHNC_9bFgzSKchuugCQ',
    appId: '1:173451887290:ios:2af2ba61157b658d8a3883',
    messagingSenderId: '173451887290',
    projectId: 'gooddeeds-app-4303c',
    storageBucket: 'gooddeeds-app-4303c.firebasestorage.app',
    iosBundleId: 'com.example.gooddeedsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv6z3xYtiiqLv4GHNC_9bFgzSKchuugCQ',
    appId: '1:173451887290:ios:2af2ba61157b658d8a3883',
    messagingSenderId: '173451887290',
    projectId: 'gooddeeds-app-4303c',
    storageBucket: 'gooddeeds-app-4303c.firebasestorage.app',
    iosBundleId: 'com.example.gooddeedsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv37aOe7N0EcsTEepYSA96wXo2AfbytUk',
    appId: '1:173451887290:web:f2db32e4b71c215c8a3883',
    messagingSenderId: '173451887290',
    projectId: 'gooddeeds-app-4303c',
    authDomain: 'gooddeeds-app-4303c.firebaseapp.com',
    storageBucket: 'gooddeeds-app-4303c.firebasestorage.app',
    measurementId: 'G-4TQ03SBPH6',
  );

}